return {
	{
		name = "pirate",
		max_health = 8,
		xp = 4,
		level = 1,
		speed = 180,
		cooldown = 0,
		damage = 1,
		coins = 10},
	{
		name = "knight",
		max_health = 10,
		xp = 4,
		level = 1,
		speed = 360,
		cooldown = 0,
		damage = 3,
		coins = 10},
	{	
		name = "viking",
		max_health = 3,
		xp = 7,
		level = 1,
		speed = 60,
		cooldown = 0,
		damage = 1,
		coins = 15},
	{	
		name = "orc",
		max_health = 15,
		xp = 30,
		level = 2,
		speed = 200,
		cooldown = 0,
		damage = 3,
		coins = 20},
	{	
		name = "archer",
		max_health = 8,
		xp = 26,
		level = 2,
		speed = 180,
		cooldown = 0,
		damage = 2,
		coins = 15},
	{	
		name = "ninja",
		max_health = 10,
		xp = 30,
		level = 2,
		speed = 30,
		cooldown = 0,
		damage = 1,
		coins = 25},
	{	
		name = "boss",
		max_health = 50,
		xp = 0,
		speed = 40,
		cooldown = 0,
		damage = 1,
		coins = 10}
}